import type { GrammarTransformationDemo, TenseExample } from './grammar-visual.models';

/** Authored examples: no automatic conjugation or English parsing. NOW is 50 on each timeline. */
export const TENSE_EXAMPLES: readonly TenseExample[] = [
  {
    id: 'tense-past-simple',
    period: 'past',
    aspect: 'simple',
    label: 'Quá khứ đơn',
    formula: 'S + V2 / V-ed',
    sentence: {
      id: 'tense-past-simple-sentence',
      english: 'The team completed the audit yesterday.',
      vietnamese: 'Nhóm đã hoàn tất cuộc kiểm toán hôm qua.',
      clue: 'Completed là quá khứ đơn: việc đã hoàn tất ở thời điểm quá khứ.',
      syntax: [
        {
          kind: 'token',
          id: 'tense-past-simple-subject',
          text: 'The team',
          role: 'S',
          pos: 'Cụm danh từ',
          explanation: 'Team là chủ ngữ số ít; cả cụm nêu người thực hiện công việc.',
        },
        {
          kind: 'text',
          id: 'tense-past-simple-space-1',
          text: ' ',
        },
        {
          kind: 'token',
          id: 'tense-past-simple-verb',
          text: 'completed',
          role: 'V',
          pos: 'Cụm động từ',
          explanation: 'Completed là quá khứ đơn: việc đã hoàn tất ở thời điểm quá khứ.',
        },
        {
          kind: 'text',
          id: 'tense-past-simple-space-2',
          text: ' ',
        },
        {
          kind: 'token',
          id: 'tense-past-simple-object',
          text: 'the audit',
          role: 'O',
          pos: 'Cụm danh từ',
          explanation: 'Cụm danh từ làm tân ngữ của hành động chính.',
        },
        {
          kind: 'text',
          id: 'tense-past-simple-space-3',
          text: ' ',
        },
        {
          kind: 'token',
          id: 'tense-past-simple-time',
          text: 'yesterday',
          role: 'M',
          pos: 'Trạng từ thời gian',
          explanation: 'Yesterday chỉ một thời điểm quá khứ đã kết thúc.',
        },
        {
          kind: 'text',
          id: 'tense-past-simple-period',
          text: '.',
        },
      ],
    },
    description: 'Một hành động hoàn tất hôm qua, nằm hoàn toàn trước mốc hiện tại.',
    diagram: {
      shape: 'point',
      start: 20,
      end: 20,
      reference: 20,
    },
  },
  {
    id: 'tense-past-continuous',
    period: 'past',
    aspect: 'continuous',
    label: 'Quá khứ tiếp diễn',
    formula: 'S + was / were + V-ing',
    sentence: {
      id: 'tense-past-continuous-sentence',
      english: 'The team was reviewing the accounts at 10 a.m. yesterday.',
      vietnamese: 'Nhóm đang kiểm tra các tài khoản lúc 10 giờ sáng hôm qua.',
      clue: 'Was + reviewing: hành động đang diễn ra ở một thời điểm trong quá khứ.',
      syntax: [
        {
          kind: 'token',
          id: 'tense-past-continuous-subject',
          text: 'The team',
          role: 'S',
          pos: 'Cụm danh từ',
          explanation: 'Team là chủ ngữ số ít; cả cụm nêu người thực hiện công việc.',
        },
        {
          kind: 'text',
          id: 'tense-past-continuous-space-1',
          text: ' ',
        },
        {
          kind: 'token',
          id: 'tense-past-continuous-verb',
          text: 'was reviewing',
          role: 'V',
          pos: 'Cụm động từ',
          explanation: 'Was + reviewing: hành động đang diễn ra ở một thời điểm trong quá khứ.',
        },
        {
          kind: 'text',
          id: 'tense-past-continuous-space-2',
          text: ' ',
        },
        {
          kind: 'token',
          id: 'tense-past-continuous-object',
          text: 'the accounts',
          role: 'O',
          pos: 'Cụm danh từ',
          explanation: 'Cụm danh từ làm tân ngữ của hành động chính.',
        },
        {
          kind: 'text',
          id: 'tense-past-continuous-space-3',
          text: ' ',
        },
        {
          kind: 'token',
          id: 'tense-past-continuous-time',
          text: 'at 10 a.m. yesterday',
          role: 'M',
          pos: 'Cụm giới từ chỉ thời gian',
          explanation: 'Mốc 10 giờ sáng hôm qua nằm trong khoảng hành động đang diễn ra.',
        },
        {
          kind: 'text',
          id: 'tense-past-continuous-period',
          text: '.',
        },
      ],
    },
    description:
      'Việc kiểm tra đang diễn ra lúc 10 giờ sáng hôm qua; mốc quá khứ nằm trong khoảng kéo dài.',
    diagram: {
      shape: 'duration',
      start: 12,
      end: 38,
      reference: 25,
    },
  },
  {
    id: 'tense-past-perfect',
    period: 'past',
    aspect: 'perfect',
    label: 'Quá khứ hoàn thành',
    formula: 'S + had + V3',
    sentence: {
      id: 'tense-past-perfect-sentence',
      english: 'The team had completed the audit before the manager arrived.',
      vietnamese: 'Nhóm đã hoàn tất cuộc kiểm toán trước khi quản lý đến.',
      clue: 'Had + completed (V3): hoàn tất trước một sự việc khác trong quá khứ.',
      syntax: [
        {
          kind: 'token',
          id: 'tense-past-perfect-subject',
          text: 'The team',
          role: 'S',
          pos: 'Cụm danh từ',
          explanation: 'Team là chủ ngữ số ít; cả cụm nêu người thực hiện công việc.',
        },
        {
          kind: 'text',
          id: 'tense-past-perfect-space-1',
          text: ' ',
        },
        {
          kind: 'token',
          id: 'tense-past-perfect-verb',
          text: 'had completed',
          role: 'V',
          pos: 'Cụm động từ',
          explanation: 'Had + completed (V3): hoàn tất trước một sự việc khác trong quá khứ.',
        },
        {
          kind: 'text',
          id: 'tense-past-perfect-space-2',
          text: ' ',
        },
        {
          kind: 'token',
          id: 'tense-past-perfect-object',
          text: 'the audit',
          role: 'O',
          pos: 'Cụm danh từ',
          explanation: 'Cụm danh từ làm tân ngữ của hành động chính.',
        },
        {
          kind: 'text',
          id: 'tense-past-perfect-clause-space',
          text: ' ',
        },
        {
          kind: 'group',
          id: 'tense-past-perfect-time-clause',
          label: 'Mệnh đề thời gian làm mốc quá khứ',
          children: [
            {
              kind: 'text',
              id: 'tense-past-perfect-connector',
              text: 'before ',
            },
            {
              kind: 'token',
              id: 'tense-past-perfect-manager',
              text: 'the manager',
              role: 'S',
              pos: 'Cụm danh từ',
              explanation: 'Manager là chủ ngữ của mệnh đề làm mốc thời gian.',
            },
            {
              kind: 'text',
              id: 'tense-past-perfect-clause-space-1',
              text: ' ',
            },
            {
              kind: 'token',
              id: 'tense-past-perfect-arrival',
              text: 'arrived',
              role: 'V',
              pos: 'Cụm động từ',
              explanation:
                'Arrived là quá khứ đơn: mốc đến sau việc hoàn tất hoặc sau quá trình kéo dài.',
            },
          ],
          role: 'M',
        },
        {
          kind: 'text',
          id: 'tense-past-perfect-period',
          text: '.',
        },
      ],
    },
    description: 'Cuộc kiểm toán hoàn tất trước khi quản lý đến; cả hai mốc đều ở quá khứ.',
    diagram: {
      shape: 'perfect',
      start: 10,
      end: 25,
      reference: 35,
    },
  },
  {
    id: 'tense-past-perfect-continuous',
    period: 'past',
    aspect: 'perfect-continuous',
    label: 'Quá khứ hoàn thành tiếp diễn',
    formula: 'S + had been + V-ing',
    sentence: {
      id: 'tense-past-perfect-continuous-sentence',
      english: 'The team had been reviewing the accounts for two hours when the manager arrived.',
      vietnamese: 'Nhóm đã kiểm tra các tài khoản được hai giờ khi quản lý đến.',
      clue: 'Had been + reviewing nhấn mạnh quá trình kéo dài tới một mốc quá khứ.',
      syntax: [
        {
          kind: 'token',
          id: 'tense-past-perfect-continuous-subject',
          text: 'The team',
          role: 'S',
          pos: 'Cụm danh từ',
          explanation: 'Team là chủ ngữ số ít; cả cụm nêu người thực hiện công việc.',
        },
        {
          kind: 'text',
          id: 'tense-past-perfect-continuous-space-1',
          text: ' ',
        },
        {
          kind: 'token',
          id: 'tense-past-perfect-continuous-verb',
          text: 'had been reviewing',
          role: 'V',
          pos: 'Cụm động từ',
          explanation: 'Had been + reviewing nhấn mạnh quá trình kéo dài tới một mốc quá khứ.',
        },
        {
          kind: 'text',
          id: 'tense-past-perfect-continuous-space-2',
          text: ' ',
        },
        {
          kind: 'token',
          id: 'tense-past-perfect-continuous-object',
          text: 'the accounts',
          role: 'O',
          pos: 'Cụm danh từ',
          explanation: 'Cụm danh từ làm tân ngữ của hành động chính.',
        },
        {
          kind: 'text',
          id: 'tense-past-perfect-continuous-space-3',
          text: ' ',
        },
        {
          kind: 'token',
          id: 'tense-past-perfect-continuous-time',
          text: 'for two hours',
          role: 'M',
          pos: 'Cụm giới từ chỉ thời gian',
          explanation: 'For two hours nêu thời lượng của quá trình trước khi quản lý đến.',
        },
        {
          kind: 'text',
          id: 'tense-past-perfect-continuous-clause-space',
          text: ' ',
        },
        {
          kind: 'group',
          id: 'tense-past-perfect-continuous-time-clause',
          label: 'Mệnh đề thời gian làm mốc quá khứ',
          children: [
            {
              kind: 'text',
              id: 'tense-past-perfect-continuous-connector',
              text: 'when ',
            },
            {
              kind: 'token',
              id: 'tense-past-perfect-continuous-manager',
              text: 'the manager',
              role: 'S',
              pos: 'Cụm danh từ',
              explanation: 'Manager là chủ ngữ của mệnh đề làm mốc thời gian.',
            },
            {
              kind: 'text',
              id: 'tense-past-perfect-continuous-clause-space-1',
              text: ' ',
            },
            {
              kind: 'token',
              id: 'tense-past-perfect-continuous-arrival',
              text: 'arrived',
              role: 'V',
              pos: 'Cụm động từ',
              explanation:
                'Arrived là quá khứ đơn: mốc đến sau việc hoàn tất hoặc sau quá trình kéo dài.',
            },
          ],
          role: 'M',
        },
        {
          kind: 'text',
          id: 'tense-past-perfect-continuous-period',
          text: '.',
        },
      ],
    },
    description: 'Quá trình kiểm tra kéo dài hai giờ tới lúc quản lý đến, một mốc trước hiện tại.',
    diagram: {
      shape: 'perfect-duration',
      start: 10,
      end: 35,
      reference: 35,
    },
  },
  {
    id: 'tense-present-simple',
    period: 'present',
    aspect: 'simple',
    label: 'Hiện tại đơn',
    formula: 'S + V / V-s / V-es',
    sentence: {
      id: 'tense-present-simple-sentence',
      english: 'The team reviews the accounts every month.',
      vietnamese: 'Nhóm kiểm tra các tài khoản mỗi tháng.',
      clue: 'Reviews thêm -s theo team số ít, mô tả thói quen định kỳ.',
      syntax: [
        {
          kind: 'token',
          id: 'tense-present-simple-subject',
          text: 'The team',
          role: 'S',
          pos: 'Cụm danh từ',
          explanation: 'Team là chủ ngữ số ít; cả cụm nêu người thực hiện công việc.',
        },
        {
          kind: 'text',
          id: 'tense-present-simple-space-1',
          text: ' ',
        },
        {
          kind: 'token',
          id: 'tense-present-simple-verb',
          text: 'reviews',
          role: 'V',
          pos: 'Cụm động từ',
          explanation: 'Reviews thêm -s theo team số ít, mô tả thói quen định kỳ.',
        },
        {
          kind: 'text',
          id: 'tense-present-simple-space-2',
          text: ' ',
        },
        {
          kind: 'token',
          id: 'tense-present-simple-object',
          text: 'the accounts',
          role: 'O',
          pos: 'Cụm danh từ',
          explanation: 'Cụm danh từ làm tân ngữ của hành động chính.',
        },
        {
          kind: 'text',
          id: 'tense-present-simple-space-3',
          text: ' ',
        },
        {
          kind: 'token',
          id: 'tense-present-simple-time',
          text: 'every month',
          role: 'M',
          pos: 'Cụm danh từ chỉ thời gian',
          explanation: 'Every month là dấu hiệu của hoạt động lặp lại.',
        },
        {
          kind: 'text',
          id: 'tense-present-simple-period',
          text: '.',
        },
      ],
    },
    description: 'Việc kiểm tra lặp lại mỗi tháng; các lần xảy ra quanh mốc hiện tại.',
    diagram: {
      shape: 'routine',
      start: 15,
      end: 85,
      reference: 50,
    },
  },
  {
    id: 'tense-present-continuous',
    period: 'present',
    aspect: 'continuous',
    label: 'Hiện tại tiếp diễn',
    formula: 'S + am / is / are + V-ing',
    sentence: {
      id: 'tense-present-continuous-sentence',
      english: 'The team is reviewing the accounts now.',
      vietnamese: 'Nhóm đang kiểm tra các tài khoản lúc này.',
      clue: 'Is + reviewing: quá trình đang diễn ra ngay lúc nói.',
      syntax: [
        {
          kind: 'token',
          id: 'tense-present-continuous-subject',
          text: 'The team',
          role: 'S',
          pos: 'Cụm danh từ',
          explanation: 'Team là chủ ngữ số ít; cả cụm nêu người thực hiện công việc.',
        },
        {
          kind: 'text',
          id: 'tense-present-continuous-space-1',
          text: ' ',
        },
        {
          kind: 'token',
          id: 'tense-present-continuous-verb',
          text: 'is reviewing',
          role: 'V',
          pos: 'Cụm động từ',
          explanation: 'Is + reviewing: quá trình đang diễn ra ngay lúc nói.',
        },
        {
          kind: 'text',
          id: 'tense-present-continuous-space-2',
          text: ' ',
        },
        {
          kind: 'token',
          id: 'tense-present-continuous-object',
          text: 'the accounts',
          role: 'O',
          pos: 'Cụm danh từ',
          explanation: 'Cụm danh từ làm tân ngữ của hành động chính.',
        },
        {
          kind: 'text',
          id: 'tense-present-continuous-space-3',
          text: ' ',
        },
        {
          kind: 'token',
          id: 'tense-present-continuous-time',
          text: 'now',
          role: 'M',
          pos: 'Trạng từ thời gian',
          explanation: 'Now đặt người đọc tại mốc hiện tại.',
        },
        {
          kind: 'text',
          id: 'tense-present-continuous-period',
          text: '.',
        },
      ],
    },
    description: 'Quá trình kiểm tra đang diễn ra và đi qua mốc hiện tại.',
    diagram: {
      shape: 'duration',
      start: 30,
      end: 65,
      reference: 50,
    },
  },
  {
    id: 'tense-present-perfect',
    period: 'present',
    aspect: 'perfect',
    label: 'Hiện tại hoàn thành',
    formula: 'S + has / have + V3',
    sentence: {
      id: 'tense-present-perfect-sentence',
      english: 'The team has completed the audit.',
      vietnamese: 'Nhóm đã hoàn tất cuộc kiểm toán.',
      clue: 'Has + completed (V3): việc đã xong và kết quả còn liên quan hiện tại.',
      syntax: [
        {
          kind: 'token',
          id: 'tense-present-perfect-subject',
          text: 'The team',
          role: 'S',
          pos: 'Cụm danh từ',
          explanation: 'Team là chủ ngữ số ít; cả cụm nêu người thực hiện công việc.',
        },
        {
          kind: 'text',
          id: 'tense-present-perfect-space-1',
          text: ' ',
        },
        {
          kind: 'token',
          id: 'tense-present-perfect-verb',
          text: 'has completed',
          role: 'V',
          pos: 'Cụm động từ',
          explanation: 'Has + completed (V3): việc đã xong và kết quả còn liên quan hiện tại.',
        },
        {
          kind: 'text',
          id: 'tense-present-perfect-space-2',
          text: ' ',
        },
        {
          kind: 'token',
          id: 'tense-present-perfect-object',
          text: 'the audit',
          role: 'O',
          pos: 'Cụm danh từ',
          explanation: 'Cụm danh từ làm tân ngữ của hành động chính.',
        },
        {
          kind: 'text',
          id: 'tense-present-perfect-period',
          text: '.',
        },
      ],
    },
    description:
      'Cuộc kiểm toán hoàn tất trước hiện tại; kết quả là cuộc kiểm toán đã xong ở hiện tại.',
    diagram: {
      shape: 'perfect',
      start: 15,
      end: 40,
      reference: 50,
    },
  },
  {
    id: 'tense-present-perfect-continuous',
    period: 'present',
    aspect: 'perfect-continuous',
    label: 'Hiện tại hoàn thành tiếp diễn',
    formula: 'S + has / have been + V-ing',
    sentence: {
      id: 'tense-present-perfect-continuous-sentence',
      english: 'The team has been reviewing the accounts for two hours.',
      vietnamese: 'Nhóm đã và đang kiểm tra các tài khoản được hai giờ.',
      clue: 'Has been + reviewing: quá trình bắt đầu trước đây và tiếp tục tới hiện tại.',
      syntax: [
        {
          kind: 'token',
          id: 'tense-present-perfect-continuous-subject',
          text: 'The team',
          role: 'S',
          pos: 'Cụm danh từ',
          explanation: 'Team là chủ ngữ số ít; cả cụm nêu người thực hiện công việc.',
        },
        {
          kind: 'text',
          id: 'tense-present-perfect-continuous-space-1',
          text: ' ',
        },
        {
          kind: 'token',
          id: 'tense-present-perfect-continuous-verb',
          text: 'has been reviewing',
          role: 'V',
          pos: 'Cụm động từ',
          explanation:
            'Has been + reviewing: quá trình bắt đầu trước đây và tiếp tục tới hiện tại.',
        },
        {
          kind: 'text',
          id: 'tense-present-perfect-continuous-space-2',
          text: ' ',
        },
        {
          kind: 'token',
          id: 'tense-present-perfect-continuous-object',
          text: 'the accounts',
          role: 'O',
          pos: 'Cụm danh từ',
          explanation: 'Cụm danh từ làm tân ngữ của hành động chính.',
        },
        {
          kind: 'text',
          id: 'tense-present-perfect-continuous-space-3',
          text: ' ',
        },
        {
          kind: 'token',
          id: 'tense-present-perfect-continuous-time',
          text: 'for two hours',
          role: 'M',
          pos: 'Cụm giới từ chỉ thời gian',
          explanation: 'For two hours nêu thời lượng, không phải một mốc bắt đầu cụ thể.',
        },
        {
          kind: 'text',
          id: 'tense-present-perfect-continuous-period',
          text: '.',
        },
      ],
    },
    description: 'Quá trình kiểm tra kéo dài hai giờ từ trước tới hiện tại và vẫn đang tiếp tục.',
    diagram: {
      shape: 'perfect-duration',
      start: 20,
      end: 50,
      reference: 50,
    },
  },
  {
    id: 'tense-future-simple',
    period: 'future',
    aspect: 'simple',
    label: 'Tương lai đơn',
    formula: 'S + will + V',
    sentence: {
      id: 'tense-future-simple-sentence',
      english: 'The team will complete the audit tomorrow.',
      vietnamese: 'Nhóm sẽ hoàn tất cuộc kiểm toán ngày mai.',
      clue: 'Will + complete nguyên thể: hành động sẽ xảy ra trong tương lai.',
      syntax: [
        {
          kind: 'token',
          id: 'tense-future-simple-subject',
          text: 'The team',
          role: 'S',
          pos: 'Cụm danh từ',
          explanation: 'Team là chủ ngữ số ít; cả cụm nêu người thực hiện công việc.',
        },
        {
          kind: 'text',
          id: 'tense-future-simple-space-1',
          text: ' ',
        },
        {
          kind: 'token',
          id: 'tense-future-simple-verb',
          text: 'will complete',
          role: 'V',
          pos: 'Cụm động từ',
          explanation: 'Will + complete nguyên thể: hành động sẽ xảy ra trong tương lai.',
        },
        {
          kind: 'text',
          id: 'tense-future-simple-space-2',
          text: ' ',
        },
        {
          kind: 'token',
          id: 'tense-future-simple-object',
          text: 'the audit',
          role: 'O',
          pos: 'Cụm danh từ',
          explanation: 'Cụm danh từ làm tân ngữ của hành động chính.',
        },
        {
          kind: 'text',
          id: 'tense-future-simple-space-3',
          text: ' ',
        },
        {
          kind: 'token',
          id: 'tense-future-simple-time',
          text: 'tomorrow',
          role: 'M',
          pos: 'Trạng từ thời gian',
          explanation: 'Tomorrow đặt hành động sau mốc hiện tại.',
        },
        {
          kind: 'text',
          id: 'tense-future-simple-period',
          text: '.',
        },
      ],
    },
    description: 'Việc hoàn tất cuộc kiểm toán được dự kiến vào ngày mai, sau hiện tại.',
    diagram: {
      shape: 'point',
      start: 75,
      end: 75,
      reference: 75,
    },
  },
  {
    id: 'tense-future-continuous',
    period: 'future',
    aspect: 'continuous',
    label: 'Tương lai tiếp diễn',
    formula: 'S + will be + V-ing',
    sentence: {
      id: 'tense-future-continuous-sentence',
      english: 'The team will be reviewing the accounts at 10 a.m. tomorrow.',
      vietnamese: 'Nhóm sẽ đang kiểm tra các tài khoản lúc 10 giờ sáng mai.',
      clue: 'Will be + reviewing: quá trình sẽ đang diễn ra ở một mốc tương lai.',
      syntax: [
        {
          kind: 'token',
          id: 'tense-future-continuous-subject',
          text: 'The team',
          role: 'S',
          pos: 'Cụm danh từ',
          explanation: 'Team là chủ ngữ số ít; cả cụm nêu người thực hiện công việc.',
        },
        {
          kind: 'text',
          id: 'tense-future-continuous-space-1',
          text: ' ',
        },
        {
          kind: 'token',
          id: 'tense-future-continuous-verb',
          text: 'will be reviewing',
          role: 'V',
          pos: 'Cụm động từ',
          explanation: 'Will be + reviewing: quá trình sẽ đang diễn ra ở một mốc tương lai.',
        },
        {
          kind: 'text',
          id: 'tense-future-continuous-space-2',
          text: ' ',
        },
        {
          kind: 'token',
          id: 'tense-future-continuous-object',
          text: 'the accounts',
          role: 'O',
          pos: 'Cụm danh từ',
          explanation: 'Cụm danh từ làm tân ngữ của hành động chính.',
        },
        {
          kind: 'text',
          id: 'tense-future-continuous-space-3',
          text: ' ',
        },
        {
          kind: 'token',
          id: 'tense-future-continuous-time',
          text: 'at 10 a.m. tomorrow',
          role: 'M',
          pos: 'Cụm giới từ chỉ thời gian',
          explanation: '10 giờ sáng mai là mốc nằm trong quá trình tương lai.',
        },
        {
          kind: 'text',
          id: 'tense-future-continuous-period',
          text: '.',
        },
      ],
    },
    description:
      'Quá trình kiểm tra sẽ đang diễn ra lúc 10 giờ sáng mai; mốc tương lai nằm trong khoảng kéo dài.',
    diagram: {
      shape: 'duration',
      start: 60,
      end: 88,
      reference: 75,
    },
  },
  {
    id: 'tense-future-perfect',
    period: 'future',
    aspect: 'perfect',
    label: 'Tương lai hoàn thành',
    formula: 'S + will have + V3',
    sentence: {
      id: 'tense-future-perfect-sentence',
      english: 'The team will have completed the audit by Friday.',
      vietnamese: 'Nhóm sẽ hoàn tất cuộc kiểm toán chậm nhất vào thứ Sáu.',
      clue: 'Will have + completed (V3): hoàn tất trước hoặc chậm nhất tại một mốc tương lai.',
      syntax: [
        {
          kind: 'token',
          id: 'tense-future-perfect-subject',
          text: 'The team',
          role: 'S',
          pos: 'Cụm danh từ',
          explanation: 'Team là chủ ngữ số ít; cả cụm nêu người thực hiện công việc.',
        },
        {
          kind: 'text',
          id: 'tense-future-perfect-space-1',
          text: ' ',
        },
        {
          kind: 'token',
          id: 'tense-future-perfect-verb',
          text: 'will have completed',
          role: 'V',
          pos: 'Cụm động từ',
          explanation:
            'Will have + completed (V3): hoàn tất trước hoặc chậm nhất tại một mốc tương lai.',
        },
        {
          kind: 'text',
          id: 'tense-future-perfect-space-2',
          text: ' ',
        },
        {
          kind: 'token',
          id: 'tense-future-perfect-object',
          text: 'the audit',
          role: 'O',
          pos: 'Cụm danh từ',
          explanation: 'Cụm danh từ làm tân ngữ của hành động chính.',
        },
        {
          kind: 'text',
          id: 'tense-future-perfect-space-3',
          text: ' ',
        },
        {
          kind: 'token',
          id: 'tense-future-perfect-time',
          text: 'by Friday',
          role: 'M',
          pos: 'Cụm giới từ chỉ thời gian',
          explanation: 'By Friday nêu hạn hoàn tất; sơ đồ đặt hạn thứ Sáu sau hiện tại.',
        },
        {
          kind: 'text',
          id: 'tense-future-perfect-period',
          text: '.',
        },
      ],
    },
    description:
      'Cuộc kiểm toán sẽ hoàn tất chậm nhất vào thứ Sáu; điểm kết thúc nằm trước hạn tương lai.',
    diagram: {
      shape: 'perfect',
      start: 55,
      end: 72,
      reference: 80,
    },
  },
  {
    id: 'tense-future-perfect-continuous',
    period: 'future',
    aspect: 'perfect-continuous',
    label: 'Tương lai hoàn thành tiếp diễn',
    formula: 'S + will have been + V-ing',
    sentence: {
      id: 'tense-future-perfect-continuous-sentence',
      english: 'The team will have been reviewing the accounts for two hours by noon tomorrow.',
      vietnamese: 'Đến trưa mai, nhóm sẽ đã kiểm tra các tài khoản được hai giờ.',
      clue: 'Will have been + reviewing nhấn mạnh thời lượng tích lũy tới một mốc tương lai.',
      syntax: [
        {
          kind: 'token',
          id: 'tense-future-perfect-continuous-subject',
          text: 'The team',
          role: 'S',
          pos: 'Cụm danh từ',
          explanation: 'Team là chủ ngữ số ít; cả cụm nêu người thực hiện công việc.',
        },
        {
          kind: 'text',
          id: 'tense-future-perfect-continuous-space-1',
          text: ' ',
        },
        {
          kind: 'token',
          id: 'tense-future-perfect-continuous-verb',
          text: 'will have been reviewing',
          role: 'V',
          pos: 'Cụm động từ',
          explanation:
            'Will have been + reviewing nhấn mạnh thời lượng tích lũy tới một mốc tương lai.',
        },
        {
          kind: 'text',
          id: 'tense-future-perfect-continuous-space-2',
          text: ' ',
        },
        {
          kind: 'token',
          id: 'tense-future-perfect-continuous-object',
          text: 'the accounts',
          role: 'O',
          pos: 'Cụm danh từ',
          explanation: 'Cụm danh từ làm tân ngữ của hành động chính.',
        },
        {
          kind: 'text',
          id: 'tense-future-perfect-continuous-space-3',
          text: ' ',
        },
        {
          kind: 'token',
          id: 'tense-future-perfect-continuous-time',
          text: 'for two hours',
          role: 'M',
          pos: 'Cụm giới từ chỉ thời gian',
          explanation: 'For two hours là thời lượng tích lũy tại mốc trưa mai.',
        },
        {
          kind: 'text',
          id: 'tense-future-perfect-continuous-reference-space',
          text: ' ',
        },
        {
          kind: 'token',
          id: 'tense-future-perfect-continuous-reference',
          text: 'by noon tomorrow',
          role: 'M',
          pos: 'Cụm giới từ chỉ thời gian',
          explanation: 'By noon tomorrow đặt mốc tương lai để đo thời lượng hai giờ.',
        },
        {
          kind: 'text',
          id: 'tense-future-perfect-continuous-period',
          text: '.',
        },
      ],
    },
    description:
      'Tới trưa mai, quá trình kiểm tra sẽ kéo dài được hai giờ; thời lượng được tính tới trưa mai; hành động có thể vẫn tiếp tục.',
    diagram: {
      shape: 'perfect-duration',
      start: 58,
      end: 82,
      reference: 82,
    },
  },
];

export const PASSIVE_DEMO: GrammarTransformationDemo = {
  id: 'passive-voice',
  title: 'Từ chủ động sang bị động',
  steps: [
    {
      id: 'passive-source',
      label: '1. Nhìn câu chủ động',
      sentence: {
        id: 'passive-source-sentence',
        english: 'The accounting team sent the invoices yesterday.',
        vietnamese: 'Nhóm kế toán đã gửi các hóa đơn hôm qua.',
        clue: 'Giữ người thực hiện, đối tượng nhận hành động và mốc quá khứ khi đổi cách trình bày.',
        syntax: [
          {
            kind: 'token',
            id: 'passive-agent',
            text: 'The accounting team',
            role: 'S',
            pos: 'Cụm danh từ',
            explanation: 'Người thực hiện hành động gửi; ở câu bị động được giới thiệu bằng by.',
          },
          {
            kind: 'text',
            id: 'passive-space-1',
            text: ' ',
          },
          {
            kind: 'token',
            id: 'passive-verb',
            text: 'sent',
            role: 'V',
            pos: 'Cụm động từ',
            explanation:
              'Sent là quá khứ đơn; were sent là bị động quá khứ, were hòa hợp với invoices số nhiều.',
          },
          {
            kind: 'text',
            id: 'passive-space-2',
            text: ' ',
          },
          {
            kind: 'token',
            id: 'passive-patient',
            text: 'the invoices',
            role: 'O',
            pos: 'Cụm danh từ',
            explanation:
              'Invoices là đối tượng nhận hành động; làm tân ngữ ở câu chủ động và chủ ngữ ở câu bị động.',
          },
          {
            kind: 'text',
            id: 'passive-space-3',
            text: ' ',
          },
          {
            kind: 'token',
            id: 'passive-time',
            text: 'yesterday',
            role: 'M',
            pos: 'Trạng từ thời gian',
            explanation:
              'Yesterday giữ mốc quá khứ của câu gốc; chuyển vị trí trạng ngữ không đổi thì.',
          },
          {
            kind: 'text',
            id: 'passive-period',
            text: '.',
          },
        ],
      },
      explanation:
        'Nhóm kế toán thực hiện sent; các hóa đơn là tân ngữ nhận hành động. Yesterday cho biết câu ở quá khứ.',
    },
    {
      id: 'passive-focus',
      label: '2. Đưa đối tượng lên chủ ngữ',
      sentence: {
        id: 'passive-focus-sentence',
        english: 'The invoices were sent by the accounting team yesterday.',
        vietnamese: 'Các hóa đơn được nhóm kế toán gửi hôm qua.',
        clue: 'Giữ người thực hiện, đối tượng nhận hành động và mốc quá khứ khi đổi cách trình bày.',
        syntax: [
          {
            kind: 'token',
            id: 'passive-patient',
            text: 'The invoices',
            role: 'S',
            pos: 'Cụm danh từ',
            explanation:
              'Invoices là đối tượng nhận hành động; làm tân ngữ ở câu chủ động và chủ ngữ ở câu bị động.',
          },
          {
            kind: 'text',
            id: 'passive-space-1',
            text: ' ',
          },
          {
            kind: 'token',
            id: 'passive-verb',
            text: 'were sent',
            role: 'V',
            pos: 'Cụm động từ',
            explanation:
              'Sent là quá khứ đơn; were sent là bị động quá khứ, were hòa hợp với invoices số nhiều.',
          },
          {
            kind: 'text',
            id: 'passive-space-2',
            text: ' ',
          },
          {
            kind: 'token',
            id: 'passive-agent',
            text: 'by the accounting team',
            role: 'M',
            pos: 'Cụm giới từ',
            explanation: 'Người thực hiện hành động gửi; ở câu bị động được giới thiệu bằng by.',
          },
          {
            kind: 'text',
            id: 'passive-space-3',
            text: ' ',
          },
          {
            kind: 'token',
            id: 'passive-time',
            text: 'yesterday',
            role: 'M',
            pos: 'Trạng từ thời gian',
            explanation:
              'Yesterday giữ mốc quá khứ của câu gốc; chuyển vị trí trạng ngữ không đổi thì.',
          },
          {
            kind: 'text',
            id: 'passive-period',
            text: '.',
          },
        ],
      },
      explanation:
        'Đưa invoices lên làm chủ ngữ và đổi sent thành were sent. Dùng were vì invoices số nhiều; by giữ thông tin người gửi.',
    },
    {
      id: 'passive-context',
      label: '3. Đặt mốc thời gian lên đầu',
      sentence: {
        id: 'passive-context-sentence',
        english: 'Yesterday, the invoices were sent by the accounting team.',
        vietnamese: 'Hôm qua, các hóa đơn được nhóm kế toán gửi.',
        clue: 'Giữ người thực hiện, đối tượng nhận hành động và mốc quá khứ khi đổi cách trình bày.',
        syntax: [
          {
            kind: 'token',
            id: 'passive-time',
            text: 'Yesterday',
            role: 'M',
            pos: 'Trạng từ thời gian',
            explanation:
              'Yesterday giữ mốc quá khứ của câu gốc; chuyển vị trí trạng ngữ không đổi thì.',
          },
          {
            kind: 'text',
            id: 'passive-comma',
            text: ', ',
          },
          {
            kind: 'token',
            id: 'passive-patient',
            text: 'the invoices',
            role: 'S',
            pos: 'Cụm danh từ',
            explanation:
              'Invoices là đối tượng nhận hành động; làm tân ngữ ở câu chủ động và chủ ngữ ở câu bị động.',
          },
          {
            kind: 'text',
            id: 'passive-space-1',
            text: ' ',
          },
          {
            kind: 'token',
            id: 'passive-verb',
            text: 'were sent',
            role: 'V',
            pos: 'Cụm động từ',
            explanation:
              'Sent là quá khứ đơn; were sent là bị động quá khứ, were hòa hợp với invoices số nhiều.',
          },
          {
            kind: 'text',
            id: 'passive-space-2',
            text: ' ',
          },
          {
            kind: 'token',
            id: 'passive-agent',
            text: 'by the accounting team',
            role: 'M',
            pos: 'Cụm giới từ',
            explanation: 'Người thực hiện hành động gửi; ở câu bị động được giới thiệu bằng by.',
          },
          {
            kind: 'text',
            id: 'passive-period',
            text: '.',
          },
        ],
      },
      explanation:
        'Có thể đưa Yesterday lên đầu để làm rõ bối cảnh. Giữ by the accounting team để câu vẫn nêu đủ người thực hiện như câu gốc.',
    },
  ],
};

export const REDUCTION_DEMOS: readonly GrammarTransformationDemo[] = [
  {
    id: 'reduction-active',
    title: 'Rút gọn quan hệ chủ động',
    steps: [
      {
        id: 'reduction-active-full',
        label: '1. Mệnh đề quan hệ đầy đủ',
        sentence: {
          id: 'reduction-active-full-sentence',
          english: 'The employees who are attending the seminar will receive certificates.',
          vietnamese: 'Các nhân viên đang tham dự hội thảo sẽ nhận chứng nhận.',
          clue: 'Employees tự thực hiện attend: bỏ who are và giữ attending (V-ing).',
          syntax: [
            {
              kind: 'group',
              id: 'reduction-active-subject-group',
              label: 'Cụm chủ ngữ có phần bổ nghĩa',
              children: [
                {
                  kind: 'token',
                  id: 'reduction-active-noun',
                  text: 'The employees',
                  role: 'S',
                  pos: 'Cụm danh từ',
                  explanation: 'Employees là chủ ngữ chính và tự thực hiện việc tham dự.',
                },
                {
                  kind: 'text',
                  id: 'reduction-active-subject-space-1',
                  text: ' ',
                },
                {
                  kind: 'group',
                  id: 'reduction-active-relative-group',
                  label: 'Mệnh đề quan hệ chủ động',
                  children: [
                    {
                      kind: 'token',
                      id: 'reduction-active-relative-subject',
                      text: 'who',
                      role: 'S',
                      pos: 'Đại từ quan hệ',
                      explanation: 'Who thay cho employees, làm chủ ngữ của mệnh đề quan hệ.',
                    },
                    {
                      kind: 'text',
                      id: 'reduction-active-relative-space',
                      text: ' ',
                    },
                    {
                      kind: 'token',
                      id: 'reduction-active-relative-verb',
                      text: 'are attending',
                      role: 'V',
                      pos: 'Cụm động từ',
                      explanation:
                        'Are attending là hiện tại tiếp diễn; sau khi bỏ who are, attending trở thành cụm phân từ chủ động.',
                    },
                    {
                      kind: 'text',
                      id: 'reduction-active-relative-space-1',
                      text: ' ',
                    },
                    {
                      kind: 'token',
                      id: 'reduction-active-seminar',
                      text: 'the seminar',
                      role: 'O',
                      pos: 'Cụm danh từ',
                      explanation: 'Tân ngữ của attend trong phần bổ nghĩa cho employees.',
                    },
                  ],
                  role: 'M',
                },
              ],
              role: 'S',
            },
            {
              kind: 'text',
              id: 'reduction-active-space-1',
              text: ' ',
            },
            {
              kind: 'token',
              id: 'reduction-active-main-verb',
              text: 'will receive',
              role: 'V',
              pos: 'Cụm động từ',
              explanation:
                'Will receive là động từ chính và không thay đổi khi rút gọn phần bổ nghĩa.',
            },
            {
              kind: 'text',
              id: 'reduction-active-space-2',
              text: ' ',
            },
            {
              kind: 'token',
              id: 'reduction-active-certificates',
              text: 'certificates',
              role: 'O',
              pos: 'Cụm danh từ',
              explanation: 'Cụm danh từ làm tân ngữ của hành động chính.',
            },
            {
              kind: 'text',
              id: 'reduction-active-period',
              text: '.',
            },
          ],
        },
        explanation:
          'Xác định động từ trong mệnh đề quan hệ và động từ chính; chỉ rút gọn phần bổ nghĩa cho danh từ.',
      },
      {
        id: 'reduction-active-reduced',
        label: '2. Cụm phân từ rút gọn',
        sentence: {
          id: 'reduction-active-reduced-sentence',
          english: 'The employees attending the seminar will receive certificates.',
          vietnamese: 'Các nhân viên đang tham dự hội thảo sẽ nhận chứng nhận.',
          clue: 'Employees tự thực hiện attend: bỏ who are và giữ attending (V-ing).',
          syntax: [
            {
              kind: 'group',
              id: 'reduction-active-subject-group',
              label: 'Cụm chủ ngữ có phần bổ nghĩa',
              children: [
                {
                  kind: 'token',
                  id: 'reduction-active-noun',
                  text: 'The employees',
                  role: 'S',
                  pos: 'Cụm danh từ',
                  explanation: 'Employees là chủ ngữ chính và tự thực hiện việc tham dự.',
                },
                {
                  kind: 'text',
                  id: 'reduction-active-subject-space-1',
                  text: ' ',
                },
                {
                  kind: 'group',
                  id: 'reduction-active-relative-group',
                  label: 'Cụm phân từ chủ động',
                  children: [
                    {
                      kind: 'token',
                      id: 'reduction-active-relative-verb',
                      text: 'attending',
                      role: 'V',
                      pos: 'Hiện tại phân từ V-ing',
                      explanation:
                        'Are attending là hiện tại tiếp diễn; sau khi bỏ who are, attending trở thành cụm phân từ chủ động.',
                    },
                    {
                      kind: 'text',
                      id: 'reduction-active-relative-space-1',
                      text: ' ',
                    },
                    {
                      kind: 'token',
                      id: 'reduction-active-seminar',
                      text: 'the seminar',
                      role: 'O',
                      pos: 'Cụm danh từ',
                      explanation: 'Tân ngữ của attend trong phần bổ nghĩa cho employees.',
                    },
                  ],
                  role: 'M',
                },
              ],
              role: 'S',
            },
            {
              kind: 'text',
              id: 'reduction-active-space-1',
              text: ' ',
            },
            {
              kind: 'token',
              id: 'reduction-active-main-verb',
              text: 'will receive',
              role: 'V',
              pos: 'Cụm động từ',
              explanation:
                'Will receive là động từ chính và không thay đổi khi rút gọn phần bổ nghĩa.',
            },
            {
              kind: 'text',
              id: 'reduction-active-space-2',
              text: ' ',
            },
            {
              kind: 'token',
              id: 'reduction-active-certificates',
              text: 'certificates',
              role: 'O',
              pos: 'Cụm danh từ',
              explanation: 'Cụm danh từ làm tân ngữ của hành động chính.',
            },
            {
              kind: 'text',
              id: 'reduction-active-period',
              text: '.',
            },
          ],
        },
        explanation:
          'Bỏ who are, giữ attending (V-ing). Employees vẫn là người tham dự; will receive vẫn là động từ chính.',
      },
    ],
  },
  {
    id: 'reduction-passive',
    title: 'Rút gọn quan hệ bị động',
    steps: [
      {
        id: 'reduction-passive-full',
        label: '1. Mệnh đề quan hệ đầy đủ',
        sentence: {
          id: 'reduction-passive-full-sentence',
          english: 'The documents which are attached to the email are confidential.',
          vietnamese: 'Các tài liệu được đính kèm email là tài liệu bảo mật.',
          clue: 'Documents nhận hành động attach: bỏ which are và giữ attached (V3).',
          syntax: [
            {
              kind: 'group',
              id: 'reduction-passive-subject-group',
              label: 'Cụm chủ ngữ có phần bổ nghĩa',
              children: [
                {
                  kind: 'token',
                  id: 'reduction-passive-noun',
                  text: 'The documents',
                  role: 'S',
                  pos: 'Cụm danh từ',
                  explanation: 'Documents là chủ ngữ chính và nhận hành động đính kèm.',
                },
                {
                  kind: 'text',
                  id: 'reduction-passive-subject-space-1',
                  text: ' ',
                },
                {
                  kind: 'group',
                  id: 'reduction-passive-relative-group',
                  label: 'Mệnh đề quan hệ bị động',
                  children: [
                    {
                      kind: 'token',
                      id: 'reduction-passive-relative-subject',
                      text: 'which',
                      role: 'S',
                      pos: 'Đại từ quan hệ',
                      explanation:
                        'Which thay cho documents, làm chủ ngữ của mệnh đề quan hệ bị động.',
                    },
                    {
                      kind: 'text',
                      id: 'reduction-passive-relative-space',
                      text: ' ',
                    },
                    {
                      kind: 'token',
                      id: 'reduction-passive-relative-verb',
                      text: 'are attached',
                      role: 'V',
                      pos: 'Cụm động từ',
                      explanation:
                        'Are attached là bị động hiện tại; bỏ which are và giữ attached (V3).',
                    },
                    {
                      kind: 'text',
                      id: 'reduction-passive-relative-space-1',
                      text: ' ',
                    },
                    {
                      kind: 'token',
                      id: 'reduction-passive-email',
                      text: 'to the email',
                      role: 'M',
                      pos: 'Cụm giới từ',
                      explanation: 'Cụm giới từ bổ nghĩa attached, giữ nguyên khi rút gọn.',
                    },
                  ],
                  role: 'M',
                },
              ],
              role: 'S',
            },
            {
              kind: 'text',
              id: 'reduction-passive-space-1',
              text: ' ',
            },
            {
              kind: 'token',
              id: 'reduction-passive-main-verb',
              text: 'are',
              role: 'V',
              pos: 'Cụm động từ',
              explanation: 'Are là động từ chính, chia theo documents số nhiều.',
            },
            {
              kind: 'text',
              id: 'reduction-passive-space-2',
              text: ' ',
            },
            {
              kind: 'token',
              id: 'reduction-passive-complement',
              text: 'confidential',
              role: 'C',
              pos: 'Tính từ',
              explanation: 'Confidential là bổ ngữ của chủ ngữ documents.',
            },
            {
              kind: 'text',
              id: 'reduction-passive-period',
              text: '.',
            },
          ],
        },
        explanation:
          'Xác định động từ trong mệnh đề quan hệ và động từ chính; chỉ rút gọn phần bổ nghĩa cho danh từ.',
      },
      {
        id: 'reduction-passive-reduced',
        label: '2. Cụm phân từ rút gọn',
        sentence: {
          id: 'reduction-passive-reduced-sentence',
          english: 'The documents attached to the email are confidential.',
          vietnamese: 'Các tài liệu được đính kèm email là tài liệu bảo mật.',
          clue: 'Documents nhận hành động attach: bỏ which are và giữ attached (V3).',
          syntax: [
            {
              kind: 'group',
              id: 'reduction-passive-subject-group',
              label: 'Cụm chủ ngữ có phần bổ nghĩa',
              children: [
                {
                  kind: 'token',
                  id: 'reduction-passive-noun',
                  text: 'The documents',
                  role: 'S',
                  pos: 'Cụm danh từ',
                  explanation: 'Documents là chủ ngữ chính và nhận hành động đính kèm.',
                },
                {
                  kind: 'text',
                  id: 'reduction-passive-subject-space-1',
                  text: ' ',
                },
                {
                  kind: 'group',
                  id: 'reduction-passive-relative-group',
                  label: 'Cụm phân từ bị động',
                  children: [
                    {
                      kind: 'token',
                      id: 'reduction-passive-relative-verb',
                      text: 'attached',
                      role: 'V',
                      pos: 'Quá khứ phân từ V3',
                      explanation:
                        'Are attached là bị động hiện tại; bỏ which are và giữ attached (V3).',
                    },
                    {
                      kind: 'text',
                      id: 'reduction-passive-relative-space-1',
                      text: ' ',
                    },
                    {
                      kind: 'token',
                      id: 'reduction-passive-email',
                      text: 'to the email',
                      role: 'M',
                      pos: 'Cụm giới từ',
                      explanation: 'Cụm giới từ bổ nghĩa attached, giữ nguyên khi rút gọn.',
                    },
                  ],
                  role: 'M',
                },
              ],
              role: 'S',
            },
            {
              kind: 'text',
              id: 'reduction-passive-space-1',
              text: ' ',
            },
            {
              kind: 'token',
              id: 'reduction-passive-main-verb',
              text: 'are',
              role: 'V',
              pos: 'Cụm động từ',
              explanation: 'Are là động từ chính, chia theo documents số nhiều.',
            },
            {
              kind: 'text',
              id: 'reduction-passive-space-2',
              text: ' ',
            },
            {
              kind: 'token',
              id: 'reduction-passive-complement',
              text: 'confidential',
              role: 'C',
              pos: 'Tính từ',
              explanation: 'Confidential là bổ ngữ của chủ ngữ documents.',
            },
            {
              kind: 'text',
              id: 'reduction-passive-period',
              text: '.',
            },
          ],
        },
        explanation:
          'Bỏ which are, giữ attached (V3). Documents vẫn nhận hành động đính kèm; are confidential là vị ngữ chính.',
      },
    ],
  },
];
