import type { GrammarLesson } from './grammar-lessons';

/** Authored explanations and exercises based on reviewed Hacker 3 topic coverage, not copied questions. */
export const HACKER_GRAMMAR_LESSONS: readonly GrammarLesson[] = [
  {
    slug: 'other-another-va-dai-tu-bat-dinh',
    title: 'Other, another & đại từ bất định',
    stage: 'Nền tảng',
    summary: 'Phân biệt từ đứng trước danh từ với đại từ đứng một mình.',
    goal: 'Chọn other, another, others, those và đại từ tương hỗ theo cấu trúc.',
    part: 'part-5',
    rules: [
      {
        label: 'Một đối tượng khác',
        pattern: 'another + singular countable noun',
        use: 'Another chỉ thêm một hoặc một đối tượng khác chưa xác định; the other chỉ đối tượng còn lại trong hai đối tượng đã xác định.',
      },
      {
        label: 'Nhiều đối tượng khác',
        pattern: 'other + plural noun; others; the others',
        use: 'Other cần danh từ đi sau; others thay cho các đối tượng khác; the others chỉ những đối tượng còn lại trong một nhóm đã xác định. Other cũng có thể đứng trước danh từ không đếm được, như other information.',
      },
      {
        label: 'Người được mô tả',
        pattern: 'anyone who + singular verb; those who + plural verb',
        use: 'Anyone chỉ bất cứ người nào và đi với động từ số ít; those có thể chỉ những người được mô tả ở phía sau.',
      },
      {
        label: 'Tương hỗ và phản thân',
        pattern: 'help one another / each other; introduce oneself',
        use: 'One another và each other diễn tả tác động qua lại; đại từ phản thân diễn tả hành động hướng về chính chủ ngữ. By oneself có nghĩa là một mình hoặc tự làm.',
      },
    ],
    examples: [
      {
        ruleLabel: 'Nhiều đối tượng khác',
        id: 'other-another-va-dai-tu-bat-dinh-example-1',
        english: 'Some files are ready; others need approval.',
        syntax: [
          {
            id: 'other-another-va-dai-tu-bat-dinh-example-1-node-1',
            kind: 'group',
            label: 'Mệnh đề về nhóm thứ nhất',
            children: [
              {
                id: 'other-another-va-dai-tu-bat-dinh-example-1-node-2',
                kind: 'token',
                text: 'Some files',
                role: 'S',
                pos: 'Cụm danh từ',
                explanation: 'Some là lượng từ đứng trước files số nhiều.',
              },
              {
                id: 'other-another-va-dai-tu-bat-dinh-example-1-node-3',
                kind: 'text',
                text: ' ',
              },
              {
                id: 'other-another-va-dai-tu-bat-dinh-example-1-node-4',
                kind: 'token',
                text: 'are',
                role: 'V',
                pos: 'Cụm động từ',
                explanation: 'Are hòa hợp với files số nhiều.',
              },
              {
                id: 'other-another-va-dai-tu-bat-dinh-example-1-node-5',
                kind: 'text',
                text: ' ',
              },
              {
                id: 'other-another-va-dai-tu-bat-dinh-example-1-node-6',
                kind: 'token',
                text: 'ready',
                role: 'C',
                pos: 'Cụm tính từ',
                explanation: 'Bổ ngữ mô tả trạng thái hoặc đặc điểm của chủ ngữ.',
              },
            ],
          },
          {
            id: 'other-another-va-dai-tu-bat-dinh-example-1-node-7',
            kind: 'text',
            text: '; ',
          },
          {
            id: 'other-another-va-dai-tu-bat-dinh-example-1-node-8',
            kind: 'group',
            label: 'Mệnh đề về các hồ sơ khác',
            children: [
              {
                id: 'other-another-va-dai-tu-bat-dinh-example-1-node-9',
                kind: 'token',
                text: 'others',
                role: 'S',
                pos: 'Đại từ bất định',
                explanation: 'Others đứng độc lập thay cho other files, làm chủ ngữ số nhiều.',
                distractor: 'Không đặt danh từ sau others; dùng other files.',
              },
              {
                id: 'other-another-va-dai-tu-bat-dinh-example-1-node-10',
                kind: 'text',
                text: ' ',
              },
              {
                id: 'other-another-va-dai-tu-bat-dinh-example-1-node-11',
                kind: 'token',
                text: 'need',
                role: 'V',
                pos: 'Cụm động từ',
                explanation: 'Need không thêm -s vì others số nhiều.',
              },
              {
                id: 'other-another-va-dai-tu-bat-dinh-example-1-node-12',
                kind: 'text',
                text: ' ',
              },
              {
                id: 'other-another-va-dai-tu-bat-dinh-example-1-node-13',
                kind: 'token',
                text: 'approval',
                role: 'O',
                pos: 'Cụm danh từ',
                explanation: 'Danh từ chỉ việc phê duyệt.',
                wordFormation: 'approve → approval',
              },
            ],
          },
          {
            id: 'other-another-va-dai-tu-bat-dinh-example-1-node-14',
            kind: 'text',
            text: '.',
          },
        ],
        vietnamese: 'Một số hồ sơ đã sẵn sàng; các hồ sơ khác cần phê duyệt.',
        clue: 'Others đứng một mình và thay cho other files.',
      },
      {
        ruleLabel: 'Tương hỗ và phản thân',
        id: 'other-another-va-dai-tu-bat-dinh-example-2',
        english: 'The colleagues help one another during busy periods.',
        syntax: [
          {
            id: 'other-another-va-dai-tu-bat-dinh-example-2-node-1',
            kind: 'token',
            text: 'The colleagues',
            role: 'S',
            pos: 'Cụm danh từ',
            explanation: 'Cụm danh từ làm chủ ngữ, nêu người hoặc sự vật được nói đến.',
          },
          {
            id: 'other-another-va-dai-tu-bat-dinh-example-2-node-2',
            kind: 'text',
            text: ' ',
          },
          {
            id: 'other-another-va-dai-tu-bat-dinh-example-2-node-3',
            kind: 'token',
            text: 'help',
            role: 'V',
            pos: 'Cụm động từ',
            explanation: 'Cụm động từ chính nêu hành động hoặc trạng thái của chủ ngữ.',
          },
          {
            id: 'other-another-va-dai-tu-bat-dinh-example-2-node-4',
            kind: 'text',
            text: ' ',
          },
          {
            id: 'other-another-va-dai-tu-bat-dinh-example-2-node-5',
            kind: 'token',
            text: 'one another',
            role: 'O',
            pos: 'Đại từ tương hỗ',
            explanation: 'Tân ngữ one another diễn tả các đồng nghiệp giúp nhau.',
            distractor: 'Themselves hướng tác động về chính mỗi người; one another nêu sự qua lại.',
          },
          {
            id: 'other-another-va-dai-tu-bat-dinh-example-2-node-6',
            kind: 'text',
            text: ' ',
          },
          {
            id: 'other-another-va-dai-tu-bat-dinh-example-2-node-7',
            kind: 'token',
            text: 'during busy periods',
            role: 'M',
            pos: 'Cụm giới từ',
            explanation: 'During + cụm danh từ nêu khoảng thời gian bận rộn.',
          },
          {
            id: 'other-another-va-dai-tu-bat-dinh-example-2-node-8',
            kind: 'text',
            text: '.',
          },
        ],
        vietnamese: 'Các đồng nghiệp giúp đỡ lẫn nhau trong thời gian bận rộn.',
        clue: 'Họ giúp nhau, nên dùng đại từ tương hỗ.',
      },
    ],
    trap: 'Không dùng others documents; dùng other documents. Anyone who needs khác với those who need.',
    visual: {
      title: 'Chọn đại từ theo đối tượng',
      steps: [
        'Có danh từ theo sau?',
        'Một hay nhiều đối tượng?',
        'Nhóm đã xác định?',
        'Tác động vào mình hay lẫn nhau?',
      ],
    },
    checks: [
      {
        prompt: 'This monitor is faulty. Please bring _____ monitor from storage.',
        options: ['another', 'others', 'each other', 'anyone'],
        answer: 0,
        explanation: 'Monitor là danh từ đếm được số ít; another monitor là một màn hình khác.',
      },
      {
        prompt: '_____ who wishes to attend must register by Friday.',
        options: ['Those', 'Anyone', 'All', 'Others'],
        answer: 1,
        explanation:
          'Wishes là động từ số ít, phù hợp với anyone who; those/all/others who cần wish.',
      },
    ],
  },
  {
    slug: 'trang-tu-va-tu-nhan-manh',
    title: 'Trạng từ & từ nhấn mạnh',
    stage: 'Mở rộng',
    summary: 'Đọc phạm vi bổ nghĩa để hiểu mức độ, thời điểm và giới hạn.',
    goal: 'Phân biệt nearly, even, only, still, yet và trạng từ bổ nghĩa tính từ.',
    part: 'part-5',
    rules: [
      {
        label: 'Bổ nghĩa tính từ',
        pattern: 'adverb + adjective / participle adjective',
        use: 'Trạng từ diễn tả mức độ của tính từ, như fully operational hoặc overwhelmingly positive; không chọn tính từ chỉ vì chỗ trống đứng sau be.',
      },
      {
        label: 'Gần như và ngay cả',
        pattern: 'nearly / almost / practically + all; even + noun phrase',
        use: 'Nearly, almost và practically diễn tả gần như toàn bộ; even nhấn mạnh một trường hợp bất ngờ. Chọn theo nghĩa, không chỉ vị trí.',
      },
      {
        label: 'Còn và chưa',
        pattern: 'still + verb; have not + yet + V3',
        use: 'Still diễn tả tình trạng tiếp tục; not yet diễn tả việc chưa xảy ra tới thời điểm xét. Already chỉ việc đã xảy ra; yet cũng thường đứng cuối câu.',
      },
      {
        label: 'Phạm vi giới hạn',
        pattern: 'only after + event; not necessarily + adjective / V3',
        use: 'Only after giới hạn thời điểm cho phép hành động; not necessarily nghĩa là không nhất thiết. Vị trí only quyết định thành phần được giới hạn.',
      },
    ],
    examples: [
      {
        ruleLabel: 'Bổ nghĩa tính từ',
        id: 'trang-tu-va-tu-nhan-manh-example-1',
        english: 'The new payment system is fully operational.',
        syntax: [
          {
            id: 'trang-tu-va-tu-nhan-manh-example-1-node-1',
            kind: 'token',
            text: 'The new payment system',
            role: 'S',
            pos: 'Cụm danh từ',
            explanation: 'System là danh từ chính; new và payment bổ nghĩa trong cụm chủ ngữ.',
          },
          {
            id: 'trang-tu-va-tu-nhan-manh-example-1-node-2',
            kind: 'text',
            text: ' ',
          },
          {
            id: 'trang-tu-va-tu-nhan-manh-example-1-node-3',
            kind: 'token',
            text: 'is',
            role: 'V',
            pos: 'Cụm động từ',
            explanation: 'Cụm động từ chính nêu hành động hoặc trạng thái của chủ ngữ.',
          },
          {
            id: 'trang-tu-va-tu-nhan-manh-example-1-node-4',
            kind: 'text',
            text: ' ',
          },
          {
            id: 'trang-tu-va-tu-nhan-manh-example-1-node-5',
            kind: 'group',
            label: 'Cụm tính từ làm bổ ngữ',
            children: [
              {
                id: 'trang-tu-va-tu-nhan-manh-example-1-node-6',
                kind: 'token',
                text: 'fully',
                role: 'M',
                pos: 'Trạng từ',
                explanation: 'Fully là trạng từ mức độ bổ nghĩa cho operational.',
                wordFormation: 'full → fully',
                distractor:
                  'Sau is không nhất thiết chọn tính từ ngay; trước operational cần trạng từ.',
              },
              {
                id: 'trang-tu-va-tu-nhan-manh-example-1-node-7',
                kind: 'text',
                text: ' ',
              },
              {
                id: 'trang-tu-va-tu-nhan-manh-example-1-node-8',
                kind: 'token',
                text: 'operational',
                role: 'C',
                pos: 'Cụm tính từ',
                explanation: 'Tính từ chính của bổ ngữ, mô tả khả năng vận hành.',
              },
            ],
            role: 'C',
          },
          {
            id: 'trang-tu-va-tu-nhan-manh-example-1-node-9',
            kind: 'text',
            text: '.',
          },
        ],
        vietnamese: 'Hệ thống thanh toán mới đã vận hành đầy đủ.',
        clue: 'Fully bổ nghĩa cho tính từ operational.',
      },
      {
        ruleLabel: 'Phạm vi giới hạn',
        id: 'trang-tu-va-tu-nhan-manh-example-2',
        english: 'Refunds are issued only after the returned goods are inspected.',
        syntax: [
          {
            id: 'trang-tu-va-tu-nhan-manh-example-2-node-1',
            kind: 'token',
            text: 'Refunds',
            role: 'S',
            pos: 'Cụm danh từ',
            explanation: 'Cụm danh từ làm chủ ngữ, nêu người hoặc sự vật được nói đến.',
          },
          {
            id: 'trang-tu-va-tu-nhan-manh-example-2-node-2',
            kind: 'text',
            text: ' ',
          },
          {
            id: 'trang-tu-va-tu-nhan-manh-example-2-node-3',
            kind: 'token',
            text: 'are issued',
            role: 'V',
            pos: 'Cụm động từ',
            explanation: 'Bị động hiện tại: refunds nhận hành động hoàn tiền.',
          },
          {
            id: 'trang-tu-va-tu-nhan-manh-example-2-node-4',
            kind: 'text',
            text: ' ',
          },
          {
            id: 'trang-tu-va-tu-nhan-manh-example-2-node-5',
            kind: 'group',
            label: 'Mệnh đề trạng ngữ thời gian có giới hạn',
            children: [
              {
                id: 'trang-tu-va-tu-nhan-manh-example-2-node-6',
                kind: 'token',
                text: 'only',
                role: 'M',
                pos: 'Trạng từ nhấn mạnh',
                explanation: 'Only giới hạn thời gian: chỉ sau khi kiểm tra hàng.',
              },
              {
                id: 'trang-tu-va-tu-nhan-manh-example-2-node-7',
                kind: 'text',
                text: ' after ',
              },
              {
                id: 'trang-tu-va-tu-nhan-manh-example-2-node-8',
                kind: 'group',
                label: 'Mệnh đề sau after',
                children: [
                  {
                    id: 'trang-tu-va-tu-nhan-manh-example-2-node-9',
                    kind: 'token',
                    text: 'the returned goods',
                    role: 'S',
                    pos: 'Cụm danh từ',
                    explanation: 'Returned là tính từ phân từ bổ nghĩa goods; cả cụm là chủ ngữ.',
                  },
                  {
                    id: 'trang-tu-va-tu-nhan-manh-example-2-node-10',
                    kind: 'text',
                    text: ' ',
                  },
                  {
                    id: 'trang-tu-va-tu-nhan-manh-example-2-node-11',
                    kind: 'token',
                    text: 'are inspected',
                    role: 'V',
                    pos: 'Cụm động từ',
                    explanation: 'Bị động hiện tại: hàng được kiểm tra.',
                  },
                ],
              },
            ],
            role: 'M',
          },
          {
            id: 'trang-tu-va-tu-nhan-manh-example-2-node-12',
            kind: 'text',
            text: '.',
          },
        ],
        vietnamese: 'Tiền chỉ được hoàn sau khi hàng trả lại được kiểm tra.',
        clue: 'Only giới hạn điều kiện thời gian after, không bổ nghĩa cho goods.',
      },
    ],
    trap: 'Not necessarily guaranteed nghĩa là không nhất thiết được bảo đảm; không có nghĩa là chắc chắn không được bảo đảm.',
    visual: {
      title: 'Tìm phạm vi bổ nghĩa',
      steps: [
        'Xác định từ được bổ nghĩa',
        'Mức độ hay thời gian?',
        'Kiểm tra phủ định',
        'Đọc nghĩa cả câu',
      ],
    },
    checks: [
      {
        prompt: 'The reviews of the new service are _____ positive.',
        options: ['overwhelming', 'overwhelmingly', 'overwhelm', 'overwhelmed'],
        answer: 1,
        explanation: 'Trước tính từ positive cần trạng từ overwhelmingly chỉ mức độ.',
      },
      {
        prompt: 'The team has not _____ received the signed contract.',
        options: ['yet', 'ever since', 'soon', 'no longer'],
        answer: 0,
        explanation: 'Has not yet received diễn tả đến nay nhóm vẫn chưa nhận được hợp đồng.',
      },
    ],
  },
  {
    slug: 'lien-tu-cap-va-cau-truc-song-song',
    title: 'Liên từ cặp & cấu trúc song song',
    stage: 'Nối ý',
    summary: 'Nối các thành phần cùng chức năng và phân biệt điều kiện với lựa chọn.',
    goal: 'Dùng both–and, either–or, neither–nor, whether–or và unless đúng nghĩa.',
    part: 'part-5',
    rules: [
      {
        label: 'Liên từ cặp',
        pattern: 'both A and B; either A or B; neither A nor B',
        use: 'Both–and khẳng định cả hai; either–or đưa ra lựa chọn; neither–nor phủ định cả hai. A và B cần cùng chức năng ngữ pháp.',
      },
      {
        label: 'Song song',
        pattern: 'to review and approve; reviewing and approving',
        use: 'Nối danh từ với danh từ, cụm động từ với cụm động từ. Một to hoặc modal có thể dùng chung cho hai động từ nguyên mẫu.',
      },
      {
        label: 'Hai khả năng',
        pattern: 'whether + clause + or + alternative',
        use: 'Whether–or nêu hai khả năng, có thể mang nghĩa bất kể lựa chọn nào. Either không thay được whether khi cần một từ mở đầu mệnh đề.',
      },
      {
        label: 'Điều kiện và hậu quả',
        pattern: 'unless + clause; imperative + or + clause',
        use: 'Unless thường tương đương if not; mệnh lệnh + or có thể cảnh báo hậu quả nếu không làm. Unless otherwise stated là dạng rút gọn của unless it is otherwise stated.',
      },
    ],
    examples: [
      {
        ruleLabel: 'Song song',
        id: 'lien-tu-cap-va-cau-truc-song-song-example-1',
        english: 'The supervisor will review and approve the request.',
        syntax: [
          {
            id: 'lien-tu-cap-va-cau-truc-song-song-example-1-node-1',
            kind: 'token',
            text: 'The supervisor',
            role: 'S',
            pos: 'Cụm danh từ',
            explanation: 'Cụm danh từ làm chủ ngữ, nêu người hoặc sự vật được nói đến.',
          },
          {
            id: 'lien-tu-cap-va-cau-truc-song-song-example-1-node-2',
            kind: 'text',
            text: ' ',
          },
          {
            id: 'lien-tu-cap-va-cau-truc-song-song-example-1-node-3',
            kind: 'group',
            label: 'Hai động từ cùng dùng chung will',
            children: [
              {
                id: 'lien-tu-cap-va-cau-truc-song-song-example-1-node-4',
                kind: 'token',
                text: 'will review',
                role: 'V',
                pos: 'Cụm động từ',
                explanation: 'Will đi với động từ nguyên thể review.',
              },
              {
                id: 'lien-tu-cap-va-cau-truc-song-song-example-1-node-5',
                kind: 'text',
                text: ' and ',
              },
              {
                id: 'lien-tu-cap-va-cau-truc-song-song-example-1-node-6',
                kind: 'token',
                text: 'approve',
                role: 'V',
                pos: 'Cụm động từ',
                explanation: 'Approve song song với review và dùng chung will.',
                distractor: 'Không dùng approving hoặc approves trong cấu trúc này.',
              },
            ],
            role: 'V',
          },
          {
            id: 'lien-tu-cap-va-cau-truc-song-song-example-1-node-7',
            kind: 'text',
            text: ' ',
          },
          {
            id: 'lien-tu-cap-va-cau-truc-song-song-example-1-node-8',
            kind: 'token',
            text: 'the request',
            role: 'O',
            pos: 'Cụm danh từ',
            explanation: 'Tân ngữ dùng chung cho review và approve.',
          },
          {
            id: 'lien-tu-cap-va-cau-truc-song-song-example-1-node-9',
            kind: 'text',
            text: '.',
          },
        ],
        vietnamese: 'Người giám sát sẽ xem xét và phê duyệt yêu cầu.',
        clue: 'Will dùng chung cho hai động từ nguyên mẫu review và approve.',
      },
      {
        ruleLabel: 'Hai khả năng',
        id: 'lien-tu-cap-va-cau-truc-song-song-example-2',
        english: 'The fee is the same whether you pay online or at the counter.',
        syntax: [
          {
            id: 'lien-tu-cap-va-cau-truc-song-song-example-2-node-1',
            kind: 'token',
            text: 'The fee',
            role: 'S',
            pos: 'Cụm danh từ',
            explanation: 'Cụm danh từ làm chủ ngữ, nêu người hoặc sự vật được nói đến.',
          },
          {
            id: 'lien-tu-cap-va-cau-truc-song-song-example-2-node-2',
            kind: 'text',
            text: ' ',
          },
          {
            id: 'lien-tu-cap-va-cau-truc-song-song-example-2-node-3',
            kind: 'token',
            text: 'is',
            role: 'V',
            pos: 'Cụm động từ',
            explanation: 'Cụm động từ chính nêu hành động hoặc trạng thái của chủ ngữ.',
          },
          {
            id: 'lien-tu-cap-va-cau-truc-song-song-example-2-node-4',
            kind: 'text',
            text: ' ',
          },
          {
            id: 'lien-tu-cap-va-cau-truc-song-song-example-2-node-5',
            kind: 'token',
            text: 'the same',
            role: 'C',
            pos: 'Cụm tính từ',
            explanation: 'The same mô tả mức phí không thay đổi giữa hai lựa chọn.',
          },
          {
            id: 'lien-tu-cap-va-cau-truc-song-song-example-2-node-6',
            kind: 'text',
            text: ' ',
          },
          {
            id: 'lien-tu-cap-va-cau-truc-song-song-example-2-node-7',
            kind: 'group',
            label: 'Mệnh đề nêu hai khả năng',
            children: [
              {
                id: 'lien-tu-cap-va-cau-truc-song-song-example-2-node-8',
                kind: 'text',
                text: 'whether ',
              },
              {
                id: 'lien-tu-cap-va-cau-truc-song-song-example-2-node-9',
                kind: 'token',
                text: 'you',
                role: 'S',
                pos: 'Đại từ nhân xưng',
                explanation: 'You là chủ ngữ trong mệnh đề whether.',
              },
              {
                id: 'lien-tu-cap-va-cau-truc-song-song-example-2-node-10',
                kind: 'text',
                text: ' ',
              },
              {
                id: 'lien-tu-cap-va-cau-truc-song-song-example-2-node-11',
                kind: 'token',
                text: 'pay',
                role: 'V',
                pos: 'Cụm động từ',
                explanation: 'Động từ dùng chung cho hai cách thanh toán.',
              },
              {
                id: 'lien-tu-cap-va-cau-truc-song-song-example-2-node-12',
                kind: 'text',
                text: ' ',
              },
              {
                id: 'lien-tu-cap-va-cau-truc-song-song-example-2-node-13',
                kind: 'group',
                label: 'Hai trạng ngữ lựa chọn',
                children: [
                  {
                    id: 'lien-tu-cap-va-cau-truc-song-song-example-2-node-14',
                    kind: 'token',
                    text: 'online',
                    role: 'M',
                    pos: 'Trạng từ',
                    explanation: 'Cách thanh toán thứ nhất.',
                  },
                  {
                    id: 'lien-tu-cap-va-cau-truc-song-song-example-2-node-15',
                    kind: 'text',
                    text: ' or ',
                  },
                  {
                    id: 'lien-tu-cap-va-cau-truc-song-song-example-2-node-16',
                    kind: 'token',
                    text: 'at the counter',
                    role: 'M',
                    pos: 'Cụm giới từ',
                    explanation: 'Nơi thanh toán thứ hai.',
                  },
                ],
                role: 'M',
              },
            ],
            role: 'M',
          },
          {
            id: 'lien-tu-cap-va-cau-truc-song-song-example-2-node-17',
            kind: 'text',
            text: '.',
          },
        ],
        vietnamese: 'Mức phí như nhau dù bạn thanh toán trực tuyến hay tại quầy.',
        clue: 'Whether mở đầu mệnh đề you pay, rồi or nêu lựa chọn khác.',
      },
    ],
    trap: 'Neither of the two applicants has replied dùng neither như đại từ; neither A nor B là cấu trúc liên từ cặp.',
    visual: {
      title: 'Nối ý đúng cấu trúc',
      steps: [
        'Khẳng định hay phủ định?',
        'Cụm từ hay mệnh đề?',
        'Hai vế cùng chức năng?',
        'Lựa chọn hay điều kiện?',
      ],
    },
    checks: [
      {
        prompt: 'The report includes both the sales figures _____ the operating costs.',
        options: ['and', 'or', 'nor', 'whether'],
        answer: 0,
        explanation: 'Both kết hợp với and để nối hai cụm danh từ cùng chức năng.',
      },
      {
        prompt: 'The discount applies _____ customers pay by card or in cash.',
        options: ['either', 'whether', 'neither', 'both'],
        answer: 1,
        explanation: 'Whether mở đầu mệnh đề customers pay và kết hợp với or để nêu hai khả năng.',
      },
    ],
  },
];
